kind: Service

apiVersion: v1

metadata:
  name: helidon-base-app
  labels:
    app: helidon-base-app
spec:
  type: NodePort
  selector:
    app: helidon-base-app
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-base-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-base-app
  template:
    metadata:
      labels:
        app: helidon-base-app
        version: v1
    spec:
      containers:
      - name: helidon-base-app
        image: helidon-base-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

      - image: mysql:8.2.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim