apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql:
    CREATE DATABASE IF NOT EXISTS helidon;
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-init-volume
  labels:
    type: local
    app: mysql
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/initdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-init-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ki